name: dev
on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --silent --immutable

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

      - name: Integration Test
        uses: cypress-io/github-action@v5
        with:
          config: baseUrl=http://localhost:3000
          quiet: false
          browser: chrome
          headless: true
          record: false
          start: npm start
          wait-on: http://localhost:3000
          wait-on-timeout: 180

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@master

      - name: Install Netlify
        run: npm install -g netlify-cli @netlify/plugin-nextjs

      - name: Build Artifact
        run: |
          npm install
          npm run build

      - name: Deploy
        run: netlify deploy --site ${{ secrets.NETLIFY_DEV_SITE_ID }} --auth ${{ secrets.NETLIFY_AUTH_TOKEN }} --dir=.next --build --prod --message "Deploy - GitHub Actions"
