name: dev
on:
  push:
    branches:
      - main

env:
  NODE_VERSION: "18.14.0"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: Install Dependencies
        run: npm install --silent --immutable

      - name: Build
        run: npm run build

      - name: Lint
        run: npm run lint

      - name: Test
        run: npm run test:ci

  deploy:
    runs-on: ubuntu-latest
    needs: [ build ]

    steps:
      - uses: actions/checkout@master

      - name: debug
        run: |
          pwd
          ls -la

      - name: Deploy
        uses: netlify/actions/cli@master
        with:
          args: deploy --dir=.next --build --prod
        env:
          NETLIFY_SITE_ID: ${{ secrets.NETLIFY_DEV_SITE_ID }}
          NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}