name: release

on:
  workflow_dispatch:
    inputs:
      release_type:
        description: 'What type of release is this?'
        required: true
        default: 'minor'
        type: choice
        options:
          - major
          - minor
          - patch

env:
  RELEASE_TYPE: ${{ github.event.inputs.release_type }}
  VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
  VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm run build

      - name: Lint
        run: pnpm run lint

  test:
    needs: [ build ]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: pnpm/action-setup@v3
        with:
          version: 8
          run_install: |
            - recursive: true
              args: [--frozen-lockfile, --strict-peer-dependencies]

      - name: Build
        run: pnpm run build

      - name: Install Playwright Browsers
        run: npx playwright install --with-deps

      - name: Integration Test
        run: pnpm run test:e2e:ci

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: playwright-report
          path: playwright-report/
          retention-days: 30

  release:
#    needs: [ build, test ]
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create new release
        id: create_release
        uses: actions/github-script@v6
        with:
          script: |
            const script = require('./.github/workflows/scripts/create-release.js')
            await script({github, context, core})
        env:
          RELEASE_TYPE: ${{ github.event.inputs.release_type }}

      - name: Release URL
        run:
          echo "New release created at ${{ steps.create_release.outputs.release_url }}"
















